import { useEffect, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { Sprout, MapPin, ChevronDown, Globe2, UserRound, Home, Store, Mic, ScanLine, Headset, ArrowUpRight, ShieldCheck, Satellite, Coins, Menu, BarChart3, Wifi, Droplets } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { LoginModal, RequestModal } from './Modals';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
import { Connectivity } from './Connectivity';

const primary = [{ to: '/voice', hi: 'AgriSathi', en: 'AgriSathi', icon: Mic }, { to: '/monitoring', hi: 'फसल निगरानी', en: 'Monitoring', icon: Satellite }, { to: '/ledger', hi: 'लेजर', en: 'Ledger', icon: Sprout }, { to: '/credits', hi: 'क्रेडिट अवसर', en: 'Credits', icon: Coins }, { to: '/network', hi: 'BRICS नेटवर्क', en: 'Agri Network', icon: Globe2 }];
const extras = [{ to: '/', hi: 'होम', en: 'Home', icon: Home }, { to: '/advisory', hi: 'स्मार्ट सिंचाई सलाह', en: 'Smart advisory', icon: Droplets }, { to: '/analytics', hi: 'किसान एनालिटिक्स', en: 'Farmer analytics', icon: BarChart3 }, { to: '/farm', hi: 'मेरा खेत', en: 'Farmer profile', icon: UserRound }, { to: '/market', hi: 'बाज़ार और भाव', en: 'Market & prices', icon: Store }, { to: '/scanner', hi: 'फसल जाँच', en: 'Crop scanner', icon: ScanLine }, { to: '/helpline', hi: 'हेल्पलाइन', en: 'Helpline', icon: Headset }, { to: '/offline', hi: 'ऑफ़लाइन सहायता', en: 'Offline hub', icon: Wifi }];
export const Layout = ({ children }) => {
  const { t, language, setLanguage, user, setLoginOpen } = useApp(); const [menu, setMenu] = useState(false); const route = useLocation();
  useEffect(() => { window.scrollTo(0, 0); window.speechSynthesis?.cancel(); setMenu(false); }, [route.pathname]);
  const mobile = [extras[0], primary[1], primary[0], primary[2]];
  return <><div className="utility-bar"><div className="container utility-inner"><span data-testid="utility-tagline"><Sprout size={13} />{t('किसान की आवाज़। धरती का भविष्य।', 'The farmer’s voice. The earth’s future.')}</span><div className="utility-right"><span data-testid="guest-access-label"><ShieldCheck size={13} />{t('बिना लॉगिन शुरुआत', 'Start without login')}</span><span className="utility-divider" /><span data-testid="demo-mode-label">{t('हैकाथॉन प्रोटोटाइप', 'Hackathon prototype')}</span></div></div></div>
    <header className="site-header"><div className="container navbar ecosystem-navbar"><Link to="/" className="brand" data-testid="brand-link"><span className="brand-symbol"><Sprout size={29} strokeWidth={1.8} /></span><span className="brand-word">Kisan<span>Gyan</span><small>किसान मित्र</small></span></Link><nav className="desktop-nav" aria-label="Core farming features">{primary.map(item => <NavLink data-testid={`nav-${item.to.slice(1)}`} key={item.to} to={item.to}>{t(item.hi, item.en)}</NavLink>)}</nav><div className="header-actions"><button className="all-tools-button" aria-label="All tools" title="All tools" onClick={() => setMenu(true)} data-testid="all-tools-button"><Menu size={20} /></button><label className="language-control"><Globe2 size={17} /><select aria-label="App language" data-testid="language-select" value={language} onChange={e => setLanguage(e.target.value)}><option value="hi">हिन्दी</option><option value="en">English</option></select><ChevronDown size={12} /></label>{user ? <Link to="/farm" className="btn btn-primary login-btn" data-testid="profile-button"><UserRound size={16} /><span>{t('मेरा खेत', 'My farm')}</span></Link> : <button className="btn btn-primary login-btn" onClick={() => setLoginOpen(true)} data-testid="login-button"><UserRound size={16} /><span>{t('लॉगिन', 'Login')}</span></button>}</div></div></header><div className="connection-strip"><div className="container"><Connectivity /></div></div><main>{children}</main>
    <footer className="site-footer"><div className="container footer-main"><div><Link to="/" className="brand footer-brand" data-testid="footer-brand"><span className="brand-symbol"><Sprout size={29} /></span><span className="brand-word">Kisan<span>Gyan</span><small>किसान मित्र</small></span></Link><p data-testid="footer-tagline">{t('बेहतर जानकारी। सतत खेती। साझा भविष्य।', 'Better knowledge. Regenerative farming. A shared future.')}</p><span className="made-in" data-testid="made-in-india">🇮🇳 {t('किसानों के लिए, दिल से।', 'Made with care for farmers.')}</span></div><div><h3 data-testid="footer-links-heading">{t('खेती के हर कदम में साथ', 'Your farming journey')}</h3>{primary.map(i => <Link key={i.to} to={i.to} data-testid={`footer-${i.to.slice(1)}`}>{t(i.hi, i.en)}</Link>)}</div><div><h3 data-testid="footer-schemes-heading">{t('सहायता और सरकारी जानकारी', 'Support & public information')}</h3><Link to="/helpline" data-testid="footer-helpline">{t('किसान हेल्पलाइन', 'Kisan helpline')}</Link><Link to="/offline" data-testid="footer-offline">{t('ऑफ़लाइन सहायता', 'Offline hub')}</Link><a href="https://pmkisan.gov.in/" target="_blank" rel="noreferrer" data-testid="pm-kisan-link">PM-Kisan <ArrowUpRight size={13} /></a><a href="https://sfacindia.com/" target="_blank" rel="noreferrer" data-testid="fpo-link">FPO / SFAC <ArrowUpRight size={13} /></a><a href="tel:18001801551" data-testid="footer-call">1800-180-1551 <Headset size={13} /></a></div></div><div className="container footer-bottom"><span data-testid="copyright">© {new Date().getFullYear()} KisanGyan · AgriSathi</span><span data-testid="footer-disclaimer">{t('स्वतंत्र प्रोटोटाइप • सरकारी सेवा या प्रमाणित क्रेडिट मंच नहीं', 'Independent prototype · Not a government service or certified-credit platform')}</span></div></footer>
    <nav className="mobile-nav ecosystem-mobile-nav" aria-label="Mobile navigation">{mobile.map(i => <NavLink to={i.to} end={i.to === '/'} key={i.to} className={i.to === '/voice' ? 'mobile-voice' : ''} data-testid={`mobile-${i.to.slice(1) || 'home'}`}><span><i.icon size={21} /></span>{t(i.hi, i.en === 'Monitoring' ? 'Fields' : i.en)}</NavLink>)}<button onClick={() => setMenu(true)} data-testid="mobile-more"><span><Menu size={21} /></span>{t('और', 'More')}</button></nav>
    <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="eco-modal tools-modal" data-testid="all-tools-modal"><DialogTitle data-testid="all-tools-title">{t('आपका पूरा किसान साथी', 'Everything for your farm')}</DialogTitle><DialogDescription>{t('खेत से बाज़ार तक, हर कदम एक जगह।', 'From your field to the wider world.')}</DialogDescription><div className="all-tools-grid">{[...primary, ...extras].map(i => <Link key={i.to} to={i.to} onClick={() => setMenu(false)} data-testid={`tool-${i.to.slice(1) || 'home'}`}><i.icon size={21} /><span>{t(i.hi, i.en)}</span><ArrowUpRight size={13} /></Link>)}</div></DialogContent></Dialog><LoginModal /><RequestModal /></>;
};
export const LocationPicker = () => { const { location, changeLocation, t } = useApp(); return <label className="location-picker"><MapPin size={15} /><select aria-label="District" data-testid="location-select" value={location} onChange={e => changeLocation(e.target.value)}><option value="Bareilly">{t('बरेली, उत्तर प्रदेश', 'Bareilly, Uttar Pradesh')}</option><option value="Lucknow">{t('लखनऊ, उत्तर प्रदेश', 'Lucknow, Uttar Pradesh')}</option><option value="Agra">{t('आगरा, उत्तर प्रदेश', 'Agra, Uttar Pradesh')}</option></select><ChevronDown size={13} /></label>; };