import { useState } from 'react';
import { Phone, MessageCircle, Mail, Volume2 } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../ui/dialog';
import { useApp } from '../../context/AppContext';
import { speakText } from '../../lib/ecosystem';

export const ChannelDemo = () => {
  const { t, language } = useApp(); const [channel, setChannel] = useState(null); const [message, setMessage] = useState('');
  const topics = t(['फसल की पत्तियाँ जाँचें। पीलेपन के कई कारण हो सकते हैं; मिट्टी की जाँच और कृषि विशेषज्ञ की सलाह लें।', 'सिंचाई से पहले जड़ों के पास नमी और स्थानीय मौसम की जाँच करें।', 'मंडी के वास्तविक भाव बिक्री से पहले स्थानीय मंडी से पूछें।'], ['Inspect the crop leaves. Yellowing can have several causes; arrange a soil test and consult an agricultural expert.', 'Before irrigation, check root-zone moisture and the local forecast.', 'Verify actual prices with the local mandi before selling your harvest.']);
  const channels = [['ivr', Phone, 'IVR', 'Phone / IVR'], ['whatsapp', MessageCircle, 'WhatsApp', 'WhatsApp voice'], ['sms', Mail, 'SMS', 'SMS alerts']];
  return <><div className="channel-buttons">{channels.map(([key, Icon, hi, en]) => <button key={key} onClick={() => { setChannel(key); setMessage(''); }} data-testid={`channel-${key}`}><Icon size={17} /><span>{t(hi, en)}</span><small>{t('डेमो', 'Demo')}</small></button>)}</div><Dialog open={!!channel} onOpenChange={open => { if (!open) { setChannel(null); window.speechSynthesis?.cancel(); } }}><DialogContent className="eco-modal" data-testid="channel-demo-modal"><DialogTitle data-testid="channel-demo-title">{channel === 'ivr' ? t('AgriSathi IVR प्रदर्शन', 'AgriSathi IVR preview') : channel === 'whatsapp' ? 'WhatsApp voice · Demo' : 'SMS alert · Demo'}</DialogTitle><DialogDescription data-testid="channel-demo-disclaimer">{t('यह इन-ऐप प्रदर्शन है। कोई कॉल, SMS या WhatsApp संदेश नहीं भेजा जाता।', 'This is an in-app demonstration. No phone call, SMS or WhatsApp message is sent.')}</DialogDescription>{channel === 'ivr' ? <><p className="eco-body" data-testid="ivr-menu">{t('1: फसल सलाह · 2: सिंचाई · 3: मंडी · 9: दोबारा सुनें', '1: Crop care · 2: Irrigation · 3: Mandi · 9: Replay')}</p><div className="ivr-keypad">{['1', '2', '3', '9'].map(key => <button key={key} data-testid={`ivr-key-${key}`} onClick={() => { const text = key === '9' ? message || topics[0] : topics[Number(key) - 1]; setMessage(text); speakText(text, language); }}>{key}</button>)}</div></> : <button className="btn btn-primary" data-testid="channel-generate-message" onClick={() => setMessage(topics[channel === 'sms' ? 1 : 0])}>{channel === 'sms' ? t('नमूना अलर्ट देखें', 'Preview sample alert') : t('नमूना वॉइस संदेश', 'Try a sample voice message')}</button>}{message && <div className="channel-message" data-testid="channel-message"><p>{message}</p><button className="text-link" onClick={() => speakText(message, language)} data-testid="channel-replay"><Volume2 size={15} />{t('दोबारा सुनें', 'Replay')}</button></div>}</DialogContent></Dialog></>;
};