import { useMemo } from 'react';
import { geoNaturalEarth1, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import world from '../../data/world.json';

export const countries = [{ code: 'IN', id: '356', name: 'India', flag: '🇮🇳', coordinates: [78, 22] }, { code: 'BR', id: '076', name: 'Brazil', flag: '🇧🇷', coordinates: [-52, -12] }, { code: 'RU', id: '643', name: 'Russia', flag: '🇷🇺', coordinates: [90, 58] }, { code: 'CN', id: '156', name: 'China', flag: '🇨🇳', coordinates: [105, 35] }, { code: 'ZA', id: '710', name: 'South Africa', flag: '🇿🇦', coordinates: [24, -29] }];
export const NetworkMap = ({ origin, destination, onSelect }) => {
  const { shapes, projection, path } = useMemo(() => { const shapes = feature(world, world.objects.countries); const projection = geoNaturalEarth1().fitExtent([[22, 20], [878, 414]], shapes); return { shapes, projection, path: geoPath(projection) }; }, []);
  const source = countries.find(c => c.code === origin); const start = projection(source.coordinates);
  return <div className="network-map" data-testid="brics-map"><svg viewBox="0 0 900 440" role="img" aria-label="Illustrative network linking India, Brazil, Russia, China and South Africa"><g>{shapes.features.map(shape => <path d={path(shape)} key={shape.id} fill={countries.some(c => Number(c.id) === Number(shape.id)) ? '#94b7a5' : '#e3ebe4'} stroke="#f5f8f3" strokeWidth="0.6" />)}</g>{countries.filter(c => c.code !== origin).map(c => { const end = projection(c.coordinates); return <path key={c.code} d={`M${start[0]},${start[1]} Q${(start[0] + end[0]) / 2},${Math.min(start[1], end[1]) - 75} ${end[0]},${end[1]}`} fill="none" stroke={c.code === destination ? '#d99c30' : '#8ca99a'} strokeWidth={c.code === destination ? 2.5 : 1.2} strokeDasharray="5 5" className={c.code === destination ? 'active-network-line' : ''} />; })}{countries.map(c => { const [x, y] = projection(c.coordinates); return <g key={c.code} transform={`translate(${x},${y})`}><circle r="9" fill={c.code === destination ? '#efc068' : '#07543c'} stroke="white" strokeWidth="3" /><text y="-17" textAnchor="middle" className="country-map-label">{c.name}</text></g>; })}</svg><div className="network-map-countries">{countries.map(c => <button key={c.code} className={destination === c.code || origin === c.code ? 'active' : ''} data-testid={`map-country-${c.code}`} onClick={() => onSelect(c.code)} disabled={origin === c.code}>{c.flag}<span>{c.name}</span></button>)}</div><span className="network-map-caption" data-testid="brics-map-disclaimer">PROTOTYPE NETWORK · NO LIVE COUNTRY CONNECTIONS</span></div>;
};