import { useState, useEffect } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { Droplets, CloudRain, Sprout, Volume2, ArrowRight, RefreshCw, CheckCircle2 } from 'lucide-react';
import { api, errorText } from '../lib/api';
import { useApp } from '../context/AppContext';
import { EcoTitle, DemoNote, Metric, Journey } from '../components/ecosystem/Primitives';
import { toast } from '../components/ui/sonner';
import { speakText } from '../lib/ecosystem';
import { readCache, writeCache, scope } from '../lib/offlineStore';

export default function Advisory() {
  const { t, language, location } = useApp(); const [params] = useSearchParams();
  const [inputs, setInputs] = useState({ crop: 'Wheat', stage: 'Flowering', soil: 'Loam', location, moisture: 38, rain_probability: 72, crop_health: 82, previous_activity: 'None' });
  const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false); const [cached, setCached] = useState(false);
  const run = async values => { setBusy(true); try { const { data } = await api.post('/ecosystem/advisory', values); setResult(data); setDirty(false); setCached(false); await writeCache(`${scope()}:last-advisory`, data); } catch (e) { const saved = await readCache(`${scope()}:last-advisory`); if (saved && !navigator.onLine) { setResult(saved.value); setInputs(saved.value.inputs); setDirty(false); setCached(true); toast.info(t('पिछली सहेजी गई सलाह दिखाई जा रही है।', 'Showing your last saved recommendation.')); } else toast.error(errorText(e)); } finally { setBusy(false); } };
  useEffect(() => {
    let active = true;
    api.get('/ecosystem/monitoring').then(r => { if (!active) return; const field = r.data.fields.find(f => f.id === params.get('field')); const initial = { crop: field?.crop || 'Wheat', stage: 'Flowering', soil: 'Loam', location, moisture: field?.id === 'field-02' ? 22 : 38, rain_probability: 72, crop_health: field?.health[2] || 82, previous_activity: 'None' }; setInputs(initial); run(initial); }).catch(() => run(inputs));
    return () => { active = false; window.speechSynthesis?.cancel(); };
    // Field context is loaded once per selected field; form edits remain local until submitted.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params.get('field')]);
  const change = (key, value) => { setInputs(v => ({ ...v, [key]: value })); setDirty(true); };
  return <div className="container eco-page"><EcoTitle eyebrow="SMART FARM ADVISORY" title={t('हर सही कदम, सही जानकारी से।', 'Better decisions start with context.')} subtitle={t('मिट्टी, मौसम, फसल और पिछली गतिविधि — एक सलाह में।', 'Soil, weather, crop stage and past activity, brought together.')} /><Journey active={2} />
    <div className="advisory-layout"><form className="advisory-controls" onSubmit={e => { e.preventDefault(); run(inputs); }}><h2 data-testid="advisory-input-title">{t('आपके खेत का संदर्भ', 'Your field context')}</h2><div className="form-stack"><div className="form-row"><label>{t('फसल', 'Crop')}<select value={inputs.crop} data-testid="advisory-crop" onChange={e => change('crop', e.target.value)}>{['Wheat', 'Rice', 'Maize', 'Tomato', 'Mustard'].map(v => <option key={v}>{v}</option>)}</select></label><label>{t('विकास अवस्था', 'Growth stage')}<select value={inputs.stage} data-testid="advisory-stage" onChange={e => change('stage', e.target.value)}>{['Sowing', 'Vegetative', 'Flowering', 'Harvest'].map(v => <option key={v}>{v}</option>)}</select></label></div><div className="form-row"><label>{t('मिट्टी', 'Soil type')}<select value={inputs.soil} data-testid="advisory-soil" onChange={e => change('soil', e.target.value)}>{['Loam', 'Clay', 'Sandy'].map(v => <option key={v}>{v}</option>)}</select></label><label>{t('स्थान', 'Location')}<input value={inputs.location} required minLength={2} maxLength={100} data-testid="advisory-location" onChange={e => change('location', e.target.value)} /></label></div>{[['moisture', t('मिट्टी की नमी', 'Soil moisture')], ['rain_probability', t('बारिश की संभावना', 'Rain probability')], ['crop_health', t('NDVI-आधारित स्वास्थ्य', 'NDVI-style crop health')]].map(([key, label]) => <label className="range-label" key={key}><span>{label}<strong data-testid={`advisory-value-${key}`}>{inputs[key]}%</strong></span><input type="range" min="0" max="100" value={inputs[key]} onChange={e => change(key, Number(e.target.value))} data-testid={`advisory-${key}`} /></label>)}<label>{t('पिछली गतिविधि', 'Previous farming activity')}<select value={inputs.previous_activity} data-testid="advisory-activity" onChange={e => change('previous_activity', e.target.value)}>{['None', 'Irrigated recently', 'Compost applied', 'Mulch applied'].map(v => <option key={v}>{v}</option>)}</select></label><button className="btn btn-primary full" disabled={busy} data-testid="advisory-generate"><RefreshCw size={16} className={busy ? 'animate-spin' : ''} />{t('सलाह अपडेट करें', 'Update recommendation')}</button></div></form>
    <section className="advisory-output">{result ? <>
      <div className="recommendation-banner"><span className="eyebrow" data-testid="recommendation-eyebrow">{cached ? t('सहेजी गई सलाह', 'CACHED RECOMMENDATION') : t('आज की नमूना सलाह', 'TODAY’S SAMPLE RECOMMENDATION')}</span><div className="recommendation-icon"><CloudRain size={38} strokeWidth={1.4} /></div><h2 data-testid="irrigation-recommendation">{t(result.title_hi, result.title)}</h2><p data-testid="irrigation-explanation">{t(result.recommendation_hi, result.recommendation)}</p>{dirty && <span className="unsaved-hint" data-testid="advisory-stale">{t('इनपुट बदल गए हैं — सलाह अपडेट करें।', 'Inputs changed — update the recommendation.')}</span>}<button className="btn btn-outline" data-testid="replay-recommendation" onClick={() => speakText(t(result.recommendation_hi, result.recommendation), language)}><Volume2 size={16} />{t('सलाह सुनें', 'Replay advice')}</button></div>
      <div className="eco-metrics three"><Metric id="advisory-moisture" label={t('नमी', 'Soil moisture')} value={`${result.inputs.moisture}%`} icon={Droplets} /><Metric id="advisory-rain" label={t('बारिश की संभावना', 'Rain probability')} value={`${result.inputs.rain_probability}%`} icon={CloudRain} color="blue" /><Metric id="water-saving" label={t('अनुमानित बचत', 'Illustrative saving')} value={`~${result.saving_percent}%`} hint={t('गारंटी नहीं', 'Not a measured saving')} icon={Sprout} color="amber" /></div>
      <div className="recommendation-reasons"><h2 data-testid="fusion-reasons-title">{t('यह सलाह क्यों?', 'Why this recommendation?')}</h2>{t(result.reasons_hi, result.reasons).map((reason, i) => <p key={i} data-testid={`fusion-reason-${i}`}><CheckCircle2 size={16} />{reason}</p>)}</div>
      <Link to="/ledger?practice=water-saving" className="btn btn-primary" data-testid="record-advisory-action">{t('किया गया कदम दर्ज करें', 'Record an action you took')}<ArrowRight size={16} /></Link>
    </> : <div className="loading-state" data-testid="advisory-loading">{t('सलाह तैयार हो रही है…', 'Preparing a recommendation…')}</div>}</section></div>
    <DemoNote id="advisory-disclaimer">{t('नियम-आधारित प्रोटोटाइप और नमूना इनपुट; लाइव मौसम या AI नहीं। वास्तविक सिंचाई से पहले स्थानीय परिस्थितियाँ जाँचें।', 'Rule-based prototype with sample inputs, not live weather or AI. Verify local conditions before irrigation. Savings are illustrative, not measured.')}</DemoNote></div>;
}