import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Leaf, Coins, ArrowUpRight, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api, errorText, money } from '../lib/api';
import { useLedger } from '../hooks/useLedger';
import { practiceName } from '../lib/ecosystem';
import { EcoTitle, DemoNote, Metric, Journey } from '../components/ecosystem/Primitives';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../components/ui/dialog';
import { toast } from '../components/ui/sonner';
import { Loading, ErrorState } from '../components/Shared';

export default function Credits() {
  const { t, language } = useApp(); const { records, reload } = useLedger();
  const [offers, setOffers] = useState(null); const [error, setError] = useState(false); const [offer, setOffer] = useState(null); const [recordId, setRecordId] = useState(''); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false);
  const eligible = records.filter(r => r.status === 'demo_verified' && r.demo_units >= 0.1); const interests = records.filter(r => r.interest);
  const load = () => { setError(false); api.get('/ecosystem/offers').then(r => setOffers(r.data.offers)).catch(() => setError(true)); };
  useEffect(load, []);
  const selected = eligible.find(r => r.id === recordId);
  const submit = async () => { setBusy(true); try { await api.post('/ecosystem/interests', { record_id: recordId, offer_id: offer.id, acknowledge_demo: true }); setOffer(null); await reload(); toast.success(t('डेमो रुचि सहेजी गई। कोई भुगतान नहीं हुआ।', 'Demo interest saved. No payment was made.')); } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } };
  return <div className="container eco-page"><EcoTitle eyebrow="SOIL & CARBON OPPORTUNITIES" title={t('बेहतर मिट्टी। नए अवसर।', 'Healthier soil. New possibilities.')} subtitle={t('सतत खेती से संभावित मूल्य तक — एक पारदर्शी प्रदर्शन।', 'Explore the connection between regenerative farming and potential value.')} /><Journey active={4} /><div className="eco-metrics three"><Metric id="credit-balance" label={t('उपलब्ध डेमो इकाइयाँ', 'Available demo units')} value={records.filter(r => r.status === 'demo_verified').reduce((s, r) => s + r.demo_units, 0).toFixed(2)} icon={Leaf} hint={t('प्रमाणित कार्बन क्रेडिट नहीं', 'Not certified carbon credits')} /><Metric id="credit-records" label={t('योग्य रिकॉर्ड', 'Eligible demo records')} value={eligible.length} icon={ShieldCheck} color="blue" /><Metric id="credit-interests" label={t('दर्ज रुचियाँ', 'Interests recorded')} value={interests.length} icon={Coins} hint={t('कोई लेनदेन नहीं', 'No financial transactions')} color="amber" /></div><div className="eco-section-title"><h2 data-testid="offers-title">{t('प्रदर्शन बाज़ार', 'Illustrative marketplace')}</h2><Link to="/ledger" className="text-link" data-testid="credits-ledger-link">{t('मेरे रिकॉर्ड', 'My practice records')}<ArrowUpRight size={15} /></Link></div>
    {error ? <ErrorState retry={load} /> : !offers ? <Loading /> : <div className="credit-offers">{offers.map(o => <article className="credit-offer" key={o.id} data-testid={`offer-${o.id}`}><div className="offer-top"><span className="offer-flag">{o.flag}</span><span className="sample-badge">{t('काल्पनिक संस्था', 'Fictional organization')}</span></div><span className="eyebrow">{o.focus}</span><h2>{o.name}</h2><p>{o.country}</p><div className="offer-rate" data-testid={`offer-rate-${o.id}`}>{money(o.rate)}<span>{t('/ डेमो इकाई', '/ demo unit')}</span></div><small>{t('केवल संकेतात्मक राशि • वास्तविक प्रस्ताव नहीं', 'Indicative amount only · not an actual offer')}</small><button className="btn btn-outline full" data-testid={`open-offer-${o.id}`} onClick={() => { setOffer(o); setRecordId(eligible[0]?.id || ''); setConsent(false); }}>{t('अवसर देखें', 'Explore opportunity')}<ArrowUpRight size={16} /></button></article>)}</div>}
    {!!interests.length && <section className="eco-section"><h2 data-testid="saved-interests-title">{t('आपकी सहेजी गई रुचियाँ', 'Your saved demo interests')}</h2><div className="interest-list">{interests.map(r => <div key={r.id} data-testid={`saved-interest-${r.id}`}><CheckCircle2 size={19} /><div><strong>{r.interest.buyer}</strong><small>{r.interest.id} · {r.interest.units} {t('डेमो इकाइयाँ', 'demo units')}</small></div><span>{money(r.interest.indicative_value_inr)}<small>{t('केवल उदाहरण', 'illustrative only')}</small></span></div>)}</div></section>}
    <DemoNote id="credits-disclaimer">{t('कोई टोकन, प्रमाणित क्रेडिट, आय या भुगतान नहीं। ये काल्पनिक प्रस्ताव हैं; वास्तविक लाभ के लिए स्वीकृत मापन, स्वतंत्र सत्यापन और बाज़ार की शर्तें आवश्यक हैं।', 'No tokens, certified credits, income or payments are issued. These fictional offers illustrate a workflow; real benefits require approved measurement, independent verification and market eligibility.')}</DemoNote>
    <Dialog open={!!offer} onOpenChange={open => !open && setOffer(null)}><DialogContent className="eco-modal" data-testid="credit-interest-modal"><DialogTitle>{offer?.name}</DialogTitle><DialogDescription>{t('यह डेमो केवल आपकी रुचि दर्ज करता है; कोई पैसा या क्रेडिट हस्तांतरित नहीं होगा।', 'This demonstration records interest only. No money or credits will be transferred.')}</DialogDescription>{eligible.length ? <><label className="eco-select-label">{t('डेमो सत्यापित गतिविधि', 'Demo-verified practice')}<select value={recordId} onChange={e => setRecordId(e.target.value)} data-testid="credit-record-select">{eligible.map(r => <option value={r.id} key={r.id}>{practiceName(r.practice, language)} · {r.demo_units} units · {r.performed_on}</option>)}</select></label>{selected && <div className="credit-preview" data-testid="credit-interest-value"><span>{selected.demo_units} × {money(offer?.rate || 0)}</span><strong>{money(selected.demo_units * (offer?.rate || 0))}</strong><small>{t('संकेतात्मक मूल्य, देय राशि नहीं', 'Illustrative value, not a payable amount')}</small></div>}<label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} data-testid="credit-consent" /><span>{t('मैं समझता/समझती हूँ कि यह वास्तविक लेनदेन नहीं है।', 'I understand that this is not a real transaction.')}</span></label><button className="btn btn-primary full" disabled={!consent || !selected || busy || !navigator.onLine} onClick={submit} data-testid="confirm-credit-interest">{t('डेमो रुचि दर्ज करें', 'Record demo interest')}</button></> : <div className="eco-empty compact"><Leaf size={31} /><p>{t('कम से कम 0.1 डेमो इकाई वाली एक सत्यापित गतिविधि चाहिए।', 'You need a demo-verified activity with at least 0.1 illustrative units.')}</p><Link to="/ledger" onClick={() => setOffer(null)} className="btn btn-primary" data-testid="credits-start-ledger">{t('गतिविधि दर्ज करें', 'Go to your ledger')}</Link></div>}</DialogContent></Dialog>
  </div>;
}