import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Mic, Satellite, Sprout, Coins, Globe2, ArrowUpRight, CloudRain, Droplets, Leaf, BarChart3, Wifi, Phone, ScanLine, Store, Headset, ArrowRight, ShieldCheck } from 'lucide-react';
import { motion } from 'framer-motion';
import { useApp } from '../context/AppContext';
import { VoiceCompanion } from '../components/VoiceCompanion';
import { LocationPicker } from '../components/Layout';
import { FarmerSnapshot } from '../components/ecosystem/FarmerSnapshot';
import { EcoSection, DemoNote, Journey } from '../components/ecosystem/Primitives';
import { api } from '../lib/api';
import { readCache, scope } from '../lib/offlineStore';

const pillars = [
  { path: '/voice', icon: Mic, hi: 'AgriSathi वॉइस AI', en: 'AgriSathi Voice AI', hiSub: 'बोलें, सुनें, फिर सुनें', sub: 'Your voice, understood', color: 'green' },
  { path: '/monitoring', icon: Satellite, hi: 'स्मार्ट फसल निगरानी', en: 'Smart Crop Monitoring', hiSub: 'खेत की सेहत पर नज़र', sub: 'A clearer view of your field', color: 'blue' },
  { path: '/ledger', icon: Sprout, hi: 'पुनर्जीवन लेजर', en: 'Regeneration Ledger', hiSub: 'हर अच्छा कदम दर्ज करें', sub: 'Good practices, recorded', color: 'teal' },
  { path: '/credits', icon: Coins, hi: 'मिट्टी और कार्बन अवसर', en: 'Soil & Carbon Marketplace', hiSub: 'संभावित मूल्य का प्रदर्शन', sub: 'Explore illustrative value', color: 'amber' },
  { path: '/network', icon: Globe2, hi: 'BRICS कृषि नेटवर्क', en: 'BRICS Agri Network', hiSub: 'ज्ञान जुड़े, संभावनाएँ बढ़ें', sub: 'Local knowledge, connected', color: 'violet' },
];
export default function Dashboard() {
  const { t, location, user } = useApp(); const [advice, setAdvice] = useState(null);
  useEffect(() => { let active = true; const load = async () => { const saved = await readCache(`${scope()}:last-advisory`).catch(() => null); if (saved) { if (active) setAdvice(saved.value); return; } try { const { data } = await api.post('/ecosystem/advisory', { location, crop: user?.farm?.crop && ['Wheat', 'Rice', 'Maize', 'Tomato', 'Mustard'].includes(user.farm.crop) ? user.farm.crop : 'Wheat' }); if (active) setAdvice(data); } catch (_) {} }; load(); return () => { active = false; }; }, [location, user]);
  return <><div className="container welcome-row"><div><span className="welcome-label" data-testid="welcome-label">{t('नमस्ते, किसान साथी', 'Namaste, Kisan Saathi')} <span className="sun-glyph">☀</span></span><span className="welcome-sub" data-testid="welcome-subtitle">{t('आपकी आवाज़ से, एक बेहतर मौसम तक।', 'From your voice to a better growing season.')}</span></div><LocationPicker /></div><section className="home-hero ecosystem-hero"><img className="hero-photo" src="/assets/farmer.jpg" alt="Farmer standing among green crops" fetchPriority="high" /><div className="hero-shade" /><div className="container hero-content"><motion.div className="hero-copy" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><div className="hero-eyebrow" data-testid="hero-eyebrow"><span />{t('किसान की उन्नति। धरती का पुनर्जीवन।', 'FARMER FIRST. EARTH FORWARD.')}</div><h1 data-testid="hero-title">{t('आपकी आवाज़ में,', 'Your voice. Your land.')}<br /><span>{t('खेती का बेहतर कल।', 'A better way to grow.')}</span></h1><p data-testid="hero-description">{t('सही सलाह से सतत खेती तक।', 'From practical advice to regenerative action.')}<br />{t('आपका हर कदम, आपके खेत और भविष्य के लिए।', 'Every small step counts. For your farm, and our future.')}</p><div className="hero-ctas"><Link to="/voice" className="btn btn-mint" data-testid="hero-ask-button"><Mic size={18} />{t('AgriSathi से बात करें', 'Talk to AgriSathi')}<ArrowUpRight size={17} /></Link><Link to="/monitoring" className="hero-secondary" data-testid="hero-monitoring-link"><Satellite size={17} />{t('खेत की निगरानी', 'See your field')}</Link></div><div className="hero-assurances"><span><ShieldCheck size={14} />{t('बिना लॉगिन शुरुआत', 'Start without login')}</span><i /><span><Wifi size={14} />{t('कम इंटरनेट में भी साथ', 'Built for the last mile')}</span></div></motion.div><div className="hero-voice-wrap"><VoiceCompanion compact /></div></div></section>
    <div className="container eco-dashboard"><section className="pillar-grid" aria-label="Five core features">{pillars.map((p, i) => <Link to={p.path} key={p.path} className={`pillar-card ${p.color}`} data-testid={`pillar-${p.path.slice(1)}`}><div><span className="pillar-number">0{i + 1}</span><ArrowUpRight size={16} /></div><p.icon size={26} strokeWidth={1.5} /><h2>{t(p.hi, p.en)}</h2><span>{t(p.hiSub, p.sub)}</span></Link>)}</section><div className="dashboard-priority"><section className="daily-advice"><div className="eco-section-title"><span className="eyebrow" data-testid="daily-advice-label">{t('आज की नमूना सलाह', 'TODAY’S SAMPLE ADVISORY')}</span><CloudRain size={26} /></div><h2 data-testid="daily-recommendation">{advice ? t(advice.title_hi, advice.title) : t('आज सिंचाई न करें।', 'Do not irrigate today.')}</h2><p data-testid="daily-recommendation-context">{t('निर्णय से पहले स्थानीय मौसम और मिट्टी की पुष्टि करें।', 'Confirm the local forecast and root-zone moisture before acting.')}</p><div className="daily-inputs"><span><Droplets size={15} />{advice?.inputs.moisture ?? 38}% {t('नमी', 'moisture')}</span><span><CloudRain size={15} />{advice?.inputs.rain_probability ?? 72}% {t('बारिश', 'rain chance')}</span><span><Leaf size={15} />{t('नमूना परिदृश्य', 'Sample scenario')}</span></div><Link className="text-link" to="/advisory" data-testid="dashboard-irrigation-link">{t('सलाह का आधार देखें', 'See the reasoning')}<ArrowRight size={16} /></Link></section><FarmerSnapshot compact /></div>
    <section className="dashboard-journey"><div className="eco-section-title"><h2>{t('एक आवाज़ से शुरू होती है बेहतर खेती।', 'A better farming story starts with a voice.')}</h2><span className="sample-badge">{t('जुड़ा हुआ प्रोटोटाइप', 'Connected prototype')}</span></div><Journey active={0} /></section>
    <div className="dashboard-secondary"><EcoSection title={t('ऊपर से खेत की सेहत', 'The health of your field, from above')} to="/monitoring" id="dashboard-monitor"><Link className="monitor-preview" to="/monitoring" data-testid="dashboard-field-preview"><img src="/assets/field-aerial.jpg" alt="Reference aerial farmland with illustrative health overlay" loading="lazy" /><span className="preview-boundary" /><span className="preview-field-label" data-testid="dashboard-health">Field 01 <b>82%</b></span><span className="preview-map-tag">{t('नमूना NDVI', 'SAMPLE NDVI')}</span></Link><div className="preview-field-stats" data-testid="dashboard-field-stats"><span>{t('जल दबाव', 'Water stress')}<b>Low</b></span><span>{t('रोग जोखिम', 'Disease risk')}<b>Medium</b></span><span>NDVI<b>0.76</b></span></div></EcoSection>
    <EcoSection title={t('इस मौसम का एक नज़ारा', 'Your season, at a glance')} to="/analytics" id="dashboard-analytics"><div className="season-preview"><div><strong data-testid="dashboard-water-used">18,400<small> L</small></strong><span>{t('पानी का नमूना उपयोग', 'Sample water use')}</span></div><div className="mini-bars" aria-label="Illustrative declining water-use trend">{[95, 84, 74, 66, 60, 52, 44, 33].map((h, i) => <i key={i} style={{ height: `${h}%` }} />)}</div></div><div className="season-bottom" data-testid="dashboard-season-metrics"><span><b>42 kg</b>{t('खाद', 'Fertilizer')}</span><span><b>86%</b>{t('फसल स्वास्थ्य', 'Crop health')}</span><span><b>2.8 t</b>{t('उपज अनुमान', 'Estimated yield')}</span></div><Link className="text-link" to="/analytics" data-testid="dashboard-trends-link">{t('मौसम के रुझान देखें', 'Explore seasonal trends')}<ArrowUpRight size={15} /></Link></EcoSection></div>
    <section className="essentials-band"><h2 data-testid="essentials-title">{t('खेती की ज़रूरतें, हमेशा साथ', 'Your everyday farming essentials')}</h2><div>{[[Store, '/market', 'बाज़ार और भाव', 'Market & prices'], [ScanLine, '/scanner', 'फसल जाँच', 'Crop scanner'], [Headset, '/helpline', 'किसान सहायता', 'Farmer helpline'], [Wifi, '/offline', 'ऑफ़लाइन सहायता', 'Offline hub']].map(([Icon, to, hi, en]) => <Link key={to} to={to} data-testid={`essential-${to.slice(1)}`}><Icon size={20} /><span>{t(hi, en)}</span><ArrowUpRight size={15} /></Link>)}</div></section><DemoNote id="dashboard-prototype-note">{t('वॉइस, सेंसर, सैटेलाइट, क्रेडिट और नेटवर्क सलाह के आँकड़े प्रदर्शन हेतु हैं। लेजर, अनुरोध और ऑफ़लाइन सिंक वास्तव में कार्य करते हैं।', 'Advisory, field telemetry, satellite indicators, credits and network connections are illustrative. Practice records, saved requests and offline syncing are functional.')}</DemoNote></div></>;
}