import { useState } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { Plus, Sprout, CheckCircle2, Download, ArrowUpRight, ClipboardCheck, Leaf, WifiOff } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api, errorText } from '../lib/api';
import { submitDurable } from '../lib/offlineQueue';
import { useLedger } from '../hooks/useLedger';
import { practices, practiceName, statusName, downloadFile } from '../lib/ecosystem';
import { EcoTitle, DemoNote, Journey, Metric } from '../components/ecosystem/Primitives';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../components/ui/dialog';
import { toast } from '../components/ui/sonner';
import { Loading, ErrorState } from '../components/Shared';

export default function Ledger() {
  const { t, language } = useApp(); const [params, setParams] = useSearchParams();
  const { records, loading, error, reload } = useLedger();
  const [adding, setAdding] = useState(!!params.get('practice')); const [verifying, setVerifying] = useState(null); const [acknowledged, setAcknowledged] = useState(false); const [busy, setBusy] = useState(false); const [filter, setFilter] = useState('all');
  const create = async e => {
    e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); values.area_acres = Number(values.area_acres); setBusy(true);
    try { const { queued } = await submitDurable('/ecosystem/ledger', values, 'ledger'); toast.success(queued ? t('इस डिवाइस पर सहेजा गया; सिंक बाकी है।', 'Saved on this device. Waiting to sync.') : t('गतिविधि दर्ज की गई।', 'Practice recorded.')); setAdding(false); setParams({}); await reload(); } catch (err) { toast.error(errorText(err)); } finally { setBusy(false); }
  };
  const verify = async () => { setBusy(true); try { await api.post(`/ecosystem/ledger/${verifying.id}/verify`, { acknowledge_demo: true }); toast.success(t('डेमो सत्यापन पूरा हुआ।', 'Demonstration verification completed.')); setVerifying(null); reload(); } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } };
  const verified = records.filter(r => ['demo_verified', 'listed'].includes(r.status));
  const visible = records.filter(r => filter === 'all' || r.status === filter);
  return <div className="container eco-page"><EcoTitle eyebrow="REGENERATION LEDGER" title={t('अच्छी खेती का हर कदम दर्ज हो।', 'Every good practice leaves a record.')} subtitle={t('मिट्टी, पानी और आने वाली फसल के लिए आपके छोटे-बड़े कदम।', 'A living record of what you do for your soil, water and future harvests.')}><button className="btn btn-primary" data-testid="add-practice" onClick={() => setAdding(true)}><Plus size={17} />{t('गतिविधि दर्ज करें', 'Record a practice')}</button></EcoTitle><Journey active={3} />
    <div className="eco-metrics three"><Metric id="ledger-total" label={t('दर्ज गतिविधियाँ', 'Recorded practices')} value={records.length} icon={Sprout} /><Metric id="ledger-verified" label={t('डेमो सत्यापित रिकॉर्ड', 'Demo-verified records')} value={verified.length} hint={t('स्वतंत्र प्रमाणन नहीं', 'Not independent certification')} icon={ClipboardCheck} color="blue" /><Metric id="ledger-units" label={t('उपलब्ध डेमो इकाइयाँ', 'Available demo units')} value={records.filter(r => r.status === 'demo_verified').reduce((s, r) => s + r.demo_units, 0).toFixed(2)} hint={t('कार्बन क्रेडिट नहीं', 'Not certified carbon credits')} icon={Leaf} color="amber" /></div>
    <div className="ledger-toolbar"><div className="category-filters">{[['all', 'सभी', 'All records'], ['recorded', 'दर्ज', 'Recorded'], ['demo_verified', 'डेमो सत्यापित', 'Demo verified'], ['listed', 'रुचि दर्ज', 'Interest recorded']].map(([value, hi, en]) => <button key={value} className={filter === value ? 'active' : ''} data-testid={`ledger-filter-${value}`} onClick={() => setFilter(value)}>{t(hi, en)}</button>)}</div><button className="text-link" disabled={!records.length} data-testid="export-ledger" onClick={() => downloadFile(JSON.stringify(records, null, 2), 'my-regeneration-ledger.json')}><Download size={15} />{t('निर्यात', 'Export')}</button></div>
    {loading ? <Loading /> : error && !records.length ? <ErrorState retry={reload} /> : visible.length ? <div className="ledger-records">{visible.map(record => <article className="ledger-record" key={record.id} data-testid={`ledger-record-${record.id}`}><span className="practice-icon"><Sprout size={24} /></span><div className="ledger-record-main"><div className="ledger-record-heading"><h2 data-testid={`practice-title-${record.id}`}>{practiceName(record.practice, language)}</h2><span className={`record-status ${record.status}`} data-testid={`practice-status-${record.id}`}>{statusName(record.status, t)}</span></div><div className="ledger-meta" data-testid={`practice-meta-${record.id}`}><span>{record.field_id.replace('field-', 'Field ')} · {record.area_acres} acres</span><span>{record.performed_on}</span></div><p data-testid={`practice-evidence-${record.id}`}>{record.evidence}</p>{record.demo_units > 0 && <small data-testid={`practice-units-${record.id}`}>{record.demo_units.toFixed(2)} {t('डेमो इकाइयाँ · प्रमाणित लाभ नहीं', 'demo units · not a certified benefit')}</small>}</div><div className="ledger-record-action">{record.status === 'recorded' ? <button className="btn btn-outline" data-testid={`verify-${record.id}`} disabled={!navigator.onLine} onClick={() => { setVerifying(record); setAcknowledged(false); }}><ClipboardCheck size={15} />{t('डेमो सत्यापन', 'Demo verification')}</button> : record.status === 'demo_verified' ? <Link to="/credits" className="text-link" data-testid={`explore-credit-${record.id}`}>{t('अवसर देखें', 'Explore opportunities')}<ArrowUpRight size={15} /></Link> : record.status === 'queued' ? <span className="pending-label"><WifiOff size={14} />{t('सिंक बाकी', 'Waiting to sync')}</span> : record.status === 'listed' ? <span className="pending-label"><CheckCircle2 size={15} />{t('रुचि दर्ज की गई', 'Demo interest saved')}</span> : <Link to="/offline" className="text-link" data-testid={`resolve-queue-${record.id}`}>{t('अनुरोध जाँचें', 'Review request')}</Link>}</div></article>)}</div> : <div className="eco-empty" data-testid="ledger-empty"><Sprout size={38} /><h2>{t('हर मौसम की एक नई शुरुआत।', 'A fresh page for a better season.')}</h2><p>{t('अभी इस श्रेणी में कोई गतिविधि नहीं है।', 'No practices in this view yet.')}</p><button className="btn btn-primary" data-testid="empty-add-practice" onClick={() => setAdding(true)}><Plus size={16} />{t('पहली गतिविधि जोड़ें', 'Add your first practice')}</button></div>}
    <DemoNote id="ledger-disclaimer">{t('आपकी गतिविधियाँ वास्तव में सहेजी जाती हैं। सत्यापन और इकाइयाँ केवल प्रदर्शन के लिए हैं — कोई स्वतंत्र जाँच, प्रमाणन या कार्बन क्रेडिट जारी नहीं होता।', 'Your activities are genuinely saved. Verification and units demonstrate a workflow only: no independent audit, certification or carbon-credit issuance occurs.')}</DemoNote>
    <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="eco-modal" data-testid="practice-modal"><DialogTitle data-testid="practice-modal-title">{t('एक अच्छा कदम दर्ज करें', 'Record a regenerative practice')}</DialogTitle><DialogDescription>{t('वही गतिविधि दर्ज करें जो आपने वास्तव में की है।', 'Record an action you have actually completed.')}</DialogDescription><form className="form-stack" onSubmit={create}><label>{t('गतिविधि', 'Practice')}<select name="practice" data-testid="practice-type" defaultValue={practices.some(p => p[0] === params.get('practice')) ? params.get('practice') : 'water-saving'}>{practices.map(([value, hi, en]) => <option value={value} key={value}>{t(hi, en)}</option>)}</select></label><div className="form-row"><label>{t('खेत', 'Field')}<select name="field_id" data-testid="practice-field"><option value="field-01">Field 01</option><option value="field-02">Field 02</option><option value="field-03">Field 03</option></select></label><label>{t('क्षेत्रफल (एकड़)', 'Area (acres)')}<input type="number" name="area_acres" step="0.01" min="0.01" max="1000" required defaultValue="4.2" data-testid="practice-area" /></label></div><label>{t('गतिविधि की तारीख', 'Activity date')}<input type="date" name="performed_on" required defaultValue={new Date().toISOString().slice(0, 10)} max={new Date().toISOString().slice(0, 10)} data-testid="practice-date" /></label><label>{t('क्या किया? अपना विवरण दें।', 'Activity evidence / notes')}<textarea name="evidence" minLength={10} maxLength={1000} rows={3} required data-testid="practice-evidence" placeholder={t('जैसे: फसल अवशेष से मिट्टी ढकी, सिंचाई रोकी…', 'For example: retained crop residues as mulch…')} /></label><button className="btn btn-primary full" disabled={busy} data-testid="save-practice">{t('गतिविधि सहेजें', 'Save practice')}</button></form></DialogContent></Dialog>
    <Dialog open={!!verifying} onOpenChange={open => !open && setVerifying(null)}><DialogContent className="eco-modal" data-testid="verification-modal"><ClipboardCheck size={35} color="#548465" /><DialogTitle>{t('सत्यापन का प्रदर्शन', 'Demonstrate verification')}</DialogTitle><DialogDescription>{t('यह नोट्स और क्षेत्रफल पर आधारित उदाहरण है। कोई साक्ष्य जाँच, उपग्रह सत्यापन या मान्यता प्राप्त प्रमाणन नहीं किया जाएगा।', 'This example uses your notes and area. It does not audit evidence, verify satellite observations or provide accredited certification.')}</DialogDescription><label className="checkbox-label"><input type="checkbox" checked={acknowledged} onChange={e => setAcknowledged(e.target.checked)} data-testid="verification-consent" /><span>{t('मैं समझता/समझती हूँ कि यह केवल डेमो है।', 'I understand this is demonstration-only verification.')}</span></label><button className="btn btn-primary full" disabled={!acknowledged || busy} onClick={verify} data-testid="confirm-demo-verification">{t('डेमो सत्यापन पूरा करें', 'Complete demo verification')}</button></DialogContent></Dialog>
  </div>;
}