import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Satellite, Droplets, ShieldAlert, ArrowRight, Layers2, SplitSquareHorizontal, Leaf } from 'lucide-react';
import { api } from '../lib/api';
import { useApp } from '../context/AppContext';
import { Loading, ErrorState } from '../components/Shared';
import { EcoTitle, DemoNote, Metric, Journey } from '../components/ecosystem/Primitives';
import { FieldMap } from '../components/ecosystem/FieldMap';

export default function Monitoring() {
  const { t } = useApp();
  const [data, setData] = useState(null); const [error, setError] = useState(false);
  const [selected, setSelected] = useState('field-01'); const [snapshot, setSnapshot] = useState(2);
  const [mode, setMode] = useState('ndvi'); const [compare, setCompare] = useState(false);
  const load = () => { setError(false); api.get('/ecosystem/monitoring').then(r => setData(r.data)).catch(() => setError(true)); };
  useEffect(load, []);
  const field = data?.fields.find(f => f.id === selected);
  return <div className="container eco-page"><EcoTitle eyebrow="A CLEARER VIEW FROM ABOVE" title={t('अपने खेत को नई नज़र से देखें।', 'A new perspective on your land.')} subtitle={t('फसल स्वास्थ्य, पानी का दबाव और समय के साथ बदलाव।', 'Crop health, water stress and the changes that matter.')} /><Journey active={1} />
    {error ? <ErrorState retry={load} /> : !data ? <Loading /> : <><div className="monitor-toolbar"><div className="field-tabs">{data.fields.map(f => <button className={selected === f.id ? 'active' : ''} onClick={() => setSelected(f.id)} data-testid={`select-${f.id}`} key={f.id}><Leaf size={15} />{f.name}<span>{f.area_acres} ac</span></button>)}</div><div className="map-view-actions"><button data-testid="map-mode" className={mode === 'ndvi' ? 'active' : ''} onClick={() => setMode(v => v === 'ndvi' ? 'natural' : 'ndvi')}><Layers2 size={16} />{mode === 'ndvi' ? 'NDVI' : t('प्राकृतिक', 'Natural')}</button><button data-testid="map-compare" className={compare ? 'active' : ''} onClick={() => setCompare(v => !v)}><SplitSquareHorizontal size={16} />{t('तुलना', 'Compare')}</button></div></div>
      <div className="monitor-main"><div>{compare ? <div className="map-comparison"><div><span data-testid="comparison-before-label">{data.dates[0]}</span><FieldMap data={data} selected={selected} onSelect={setSelected} snapshot={0} mode={mode} compare /></div><div><span data-testid="comparison-after-label">{data.dates[snapshot]}</span><FieldMap data={data} selected={selected} onSelect={setSelected} snapshot={snapshot} mode={mode} compare /></div></div> : <FieldMap data={data} selected={selected} onSelect={setSelected} snapshot={snapshot} mode={mode} />}
      <div className="map-timeline"><div><Satellite size={16} /><span data-testid="snapshot-label">{t('नमूना अवलोकन', 'Sample observation')}</span><strong data-testid="snapshot-date">{data.dates[snapshot]}</strong></div><input type="range" min="0" max="2" step="1" value={snapshot} onChange={e => setSnapshot(Number(e.target.value))} aria-label="Observation date" data-testid="snapshot-slider" /><div className="timeline-dates">{data.dates.map((date, i) => <button key={date} onClick={() => setSnapshot(i)} className={snapshot === i ? 'active' : ''} data-testid={`snapshot-${i}`}>{date}</button>)}</div></div></div>
      <aside className="field-insights"><span className="eyebrow" data-testid="selected-field-name">{field.name} · {field.crop}</span><h2 data-testid="selected-health">{field.health[snapshot]}<span>%</span></h2><p data-testid="selected-health-label">{t('नमूना फसल स्वास्थ्य', 'Illustrative crop health')}</p><div className="health-meter"><i style={{ width: `${field.health[snapshot]}%` }} /></div><dl><div><dt>NDVI</dt><dd data-testid="field-ndvi">{field.ndvi[snapshot].toFixed(2)}</dd></div><div><dt><Droplets size={14} />{t('जल दबाव', 'Water stress')}</dt><dd data-testid="field-water-stress" className={field.stress[snapshot] === 'High' ? 'risk-high' : ''}>{field.stress[snapshot]}</dd></div><div><dt><ShieldAlert size={14} />{t('रोग जोखिम', 'Disease risk')}</dt><dd data-testid="field-disease-risk">{field.risk[snapshot]}</dd></div></dl><div className={`field-alert ${field.health[snapshot] < 65 ? 'warning' : ''}`} data-testid="field-alert">{field.health[snapshot] < 65 ? t('इस नमूने में दबाव बढ़ा है। कमज़ोर हिस्सों की जाँच करें।', 'Stress has increased in this sample. Inspect weaker patches.') : t('इस नमूने में हरियाली बेहतर है। नियमित निरीक्षण जारी रखें।', 'Vegetation is improving in this sample. Keep scouting regularly.')}</div><Link to={`/advisory?field=${field.id}`} className="btn btn-primary full" data-testid="monitoring-advisory">{t('खेत की सलाह देखें', 'Get field advice')}<ArrowRight size={16} /></Link></aside></div>
      <div className="ndvi-scale" data-testid="ndvi-legend"><span>{t('कम हरियाली', 'Lower vegetation')}</span><i /><span>{t('अच्छी हरियाली', 'Healthier vegetation')}</span></div><DemoNote id="monitoring-disclaimer">{t('उदाहरण मानचित्र और सीमाएँ, वास्तविक खेत नहीं। दोनों तारीखों में वही संदर्भ फोटो है; NDVI रंग और आँकड़े नमूना हैं। कोई लाइव सैटेलाइट निगरानी नहीं।', 'Illustrative boundaries, not your actual farm. Both dates reuse one reference photo with synthetic NDVI overlays and values. No live satellite monitoring.')}</DemoNote></>}
  </div>;
}