import { Link } from 'react-router-dom';
import { History, ShieldCheck, ArrowUpRight, Sprout } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { VoiceCompanion } from '../components/VoiceCompanion';
import { EcoTitle, DemoNote, Journey } from '../components/ecosystem/Primitives';
import { ChannelDemo } from '../components/ecosystem/ChannelDemo';

export default function Voice() {
  const { t } = useApp();
  return <div className="container eco-page"><EcoTitle eyebrow="AGRISATHI · YOUR VOICE-FIRST COMPANION" title={t('बोलिए। खेती की बात करते हैं।', 'Let’s talk about your farm.')} subtitle={t('हिन्दी और क्षेत्रीय भाषाओं में सवाल, आसान शब्दों में जवाब।', 'Ask in your language. Get simple steps, and hear them again.')} /><Journey active={0} /><div className="voice-page-grid"><VoiceCompanion /><aside className="voice-sidebar"><div className="voice-sidebar-block"><Sprout size={27} /><h2 data-testid="voice-context-title">{t('सवाल से अगले सही कदम तक', 'From a question to a practical next step')}</h2><p data-testid="voice-context-description">{t('मिट्टी, मौसम और फसल की अवस्था के साथ सिंचाई का निर्णय देखें।', 'Bring soil, weather and crop stage into your irrigation decision.')}</p><Link to="/advisory" className="text-link" data-testid="voice-smart-advisory">{t('स्मार्ट सलाह खोलें', 'Open smart advisory')}<ArrowUpRight size={16} /></Link></div><ChannelDemo /><div className="voice-sidebar-block"><History size={23} /><h2 data-testid="voice-history-title">{t('आपकी सलाह, आपके साथ', 'Your advice stays with you')}</h2><Link to="/offline" className="text-link" data-testid="voice-offline-history">{t('सहेजी गई सलाह और बाकी सवाल', 'Saved advice & pending questions')}<ArrowUpRight size={16} /></Link><p data-testid="voice-offline-description">{t('लिखे गए सवाल ऑफ़लाइन सहेजें और इंटरनेट लौटने पर सिंक करें।', 'Typed questions can be saved offline and synced when the connection returns.')}</p></div><div className="voice-safety"><ShieldCheck size={20} /><p data-testid="voice-disclaimer">{t('वॉइस इनपुट ब्राउज़र की अनुमति, भाषा और इंटरनेट समर्थन पर निर्भर है। सलाह नियम-आधारित नमूना है, वास्तविक AI निदान नहीं। दवा से पहले कृषि विशेषज्ञ से पुष्टि करें।', 'Voice input depends on browser permissions, language and connectivity. Advice is a rule-based example, not a real AI diagnosis. Consult an agricultural expert before treatment.')}</p></div></aside></div></div>;
}